import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/cn";

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", notoSans.variable)} suppressHydrationWarning>
      <TooltipProvider>
        <body>
          <ThemeProvider attribute="class" defaultTheme="light">
            {children}
            <Toaster position="top-right" richColors />
          </ThemeProvider>
        </body>
      </TooltipProvider>
    </html>
  );
}
